//login form
export const LOGIN_USERNAME_CHANGE = 'LOGIN_USERNAME_CHANGE';
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE';
export const HIDE_UNHIDE = 'HIDE_UNHIDE';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//user 
export const LOGOUT_USER = 'LOGOUT_USER';